services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: gilbertmarcel
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        RAILS_ENV: $RAILS_ENV
    depends_on:
      - db
    ports:
      - "3000:3000"
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
      args:
        RAILS_ENV: $RAILS_ENV
    depends_on:
      - app
    ports:
      - 80:80