service: gilbertmarcel
image: bolomichelin/gilbertmarcel

servers:
  web:
    - 167.99.237.140

registry:
  username: bolomichelin
  password:
    - MRSK_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: 167.99.237.140
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

accessories:
  db:
    image: postgres:15
    host: 167.99.237.140
    port: 5432
    env:
      clear:
        POSTGRES_USER: 'rails_app'
        POSTGRES_DB: 'gilbertmarcel_spina_production'
      secret:
        - POSTGRES_PASSWORD
      directories:
        - data:/var/lib/postgresql/data
